- name: Install Apache web server
  apt:
    name: apache2
    state: present
  when: install_apache_flag

- name: Combine conditions using ansible facts
  debug:
    var: ansible_facts['kernel_version']
  when:
    - ansible_facts['os_family'] == "Debian"
    - ansible_facts['distribution_major_version'] == "20"

- name: Setting complex condition
  debug:
    var: ansible_facts['kernel_version']
  when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution_major_version'] | int >= 20

- name: Register a variable
  ansible.builtin.command: cat /home/raim2007/text.txt
  register: test_file_content

- name: Use the variable in conditional statement
  debug:
    var: test_file_content.stdout
  when:
    - test_file_content is succeeded
    - "'hi' in test_file_content.stdout"

- name: Run with items greater than 5
  ansible.builtin.command: "echo {{ item }}"
  loop: [0, 2, 4, 6, 8, 10]
  when: item > 5

- name: How to use ansible_facts
  debug:
    var: ansible_facts['distribution']
  when: ansible_facts['os_family'] == "Debian"
