---
- name: Example Ansible playbook for Handlers
  hosts: all
  become: yes
  remote_user: raim2007 
  roles:
    - install-lighttpd
    #- install-apache












































